global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 60s
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'kafka'
    scrape_interval: 10s
    static_configs:
      - targets: ['kafka-1:7071']
  - job_name: 'zookeeper'
    scrape_interval: 10s
    static_configs:
      - targets: ['zk-1:7071']
  - job_name: 'kafka-connect'
    scrape_interval: 10s
    static_configs:
      - targets: ['kafka-connect:7071']